name: 2a_lift_barrier
agent_num: 2

point_shape: &point_shape [512, 3]
action_shape: &action_shape [8]

shape_meta: &shape_meta
  # acceptable types: rgb, point_cloud, low_dim
  obs:
    pointcloud:
      shape: *point_shape
      type: point_cloud
    state:
      shape: *action_shape
      type: low_dim
  action:
    shape: *action_shape

dataset:
  _target_: dataset.dataset3d.Dataset3D
  dataset_path: data/lift_barrier_pointcloud.h5
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  input_meta: 
    obs:
      pointcloud_0: *point_shape
      pointcloud_1: *point_shape
      state_0: *action_shape
      state_1: *action_shape
    action_0: *action_shape
    action_1: *action_shape
  seperate_action: True
  only_xyz: True
  use_mem: True
  
