defaults:
  - _self_
  - task: default_task

name: ${task.name}
task_name: ${task.name}
shape_meta: ${task.shape_meta}

seed: 42

horizon: 8
n_obs_steps: 3
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy:
  _target_: policy.local_dp2.DP2

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample

  obs_encoder:
    _target_: model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    rgb_model:
      _target_: model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    resize_shape: null
    crop_shape: null
    # constant center crop
    random_crop: True
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True

  optimazer_cfg: ${optimizer}
  scheduler_cfg: ${lr_scheduler}
  agent_num: ${task.agent_num}
  share_obs_encoder: False
  
  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  obs_as_global_cond: ${obs_as_global_cond}
  # crop_shape: null
  diffusion_step_embed_dim: 128
  # down_dims: [512, 1024, 2048]
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True

  # scheduler.step params
  # predict_epsilon: True

ema:
  update_after_steps: 0
  
dataloader:
  train:
    batch_size: 32
    num_workers: 8
    shuffle: True
    pin_memory: True
  val:
    batch_size: 64
    num_workers: 8
    shuffle: False
    pin_memory: True

optimizer:
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

lr_scheduler:
  scheduler: cosine
  warmup_steps: 500

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: True
  save_weights_only: False
  every_n_epochs: 1
  save_on_train_epoch_end: False
  filename: 'epoch={epoch:0>3d}-loss={val/loss:.4f}.ckpt'
  auto_insert_metric_name: False

trainer:
  max_epochs: 300
  accelerator: auto
  devices: auto
  precision: 32
  check_val_every_n_epoch: 2
  enable_progress_bar: True

logging:
  project: Local_DP2
  mode: offline
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}
  tags: ["${task_name}"]
  id: null
  group: null

multi_run:
  run_dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}

hydra:
  job:
    override_dirname: ${task_name}
  run:
    dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
  sweep:
    dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
    subdir: ${hydra.job.num}
